### ISSUE TITLE
Possible to change the tabs button orientation?

### ISSUE THREAD

**Issue by R3uan3** [ThePBone/FlatTabWidget#1]
I've modified the tab bar from labels to buttons, how i could also change their orientation from horizontal to vertical?

![image](https://user-images.githubusercontent.com/103058225/193512742-8601b8e7-c6b3-4f82-8173-816c887dccfe.png)

To this
![image](https://user-images.githubusercontent.com/103058225/193512984-d636bb1a-5b57-49ac-8962-c87788bb73ea.png)

There's a property in the `flattabwidget.h` `TabPosition tabPosition = TabPosition::Top;`
but I couldn't find anywhere in the code it being used.

**Comment by timschneeb** [comment]
I think I didn't implement `TabPosition` because I ended up not using it in my project. It would have only had a top and bottom setting, no vertical orientation anyway. This widget isn't really designed for that kind of layout, so I'm not planning to add it.

The vertical arrangement isn't easily possible without breaking the regular horizontal layout.
It would be best if you changed the start/end `QRect` bounds for the `QPropertyAnimation` of the 'separator line' in `flattabwidget.cpp` so it is animated correctly. In `flattabwidget.ui`, the 'separator line' (which is actually a label) needs its frameShape set to `VLine`, and the orientations of the spacer, separatorContainer, tabBarContainer need to be swapped and re-arranged. It's possible that other stuff needs to be fixed as well, but it's been two years since I wrote the code, so I'm not entirely sure.
